killbill/killbill-client-ruby

- lib/killbill_client/models/payment_method.rb
- spec/killbill_client/remote/model_spec.rb
This PR adds a helpful `EXTERNAL_PAYMENT` constant to the `PaymentMethod` model class, so that we don't have to keep hardcoding the magic `__EXTERNAL_PAYMENT__` string.
> Adding PaymentMethod::EXTERNAL_PAYMENT constant

- lib/killbill_client/models/account.rb
I'm getting the following exception when attempting to call `KillBillClient::Model::Account#remove_auto_pay_off`:
```
NoMethodError: undefined method `id' for "00000000-0000-0000-0000-000000000001":String
from /usr/local/var/rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/killbill-client-ruby-7cab229fb34b/lib/killbill_client/models/account.rb:121:in `remove_auto_pay_off'
```
This is because of the `AUTO_PAY_OFF_ID.id` call, which I think is just a typo.
> Fixing Account#remove_auto_pay_off

- lib/killbill_client/models/account.rb
- lib/killbill_client/models/helpers/tag_helper.rb
Calling `Account#control_tag_off?` (and any other method that calls it under the hood, like `Account#auto_pay_off?`) results in a `KillBillClient::API::NotFound` exception. This is because the parameters passed to `KillBillClient::Model::TagHelper#tags` are not correct. This PR adds the correct parameters for that call.
It also does a couple other things:
* Renames the `control_tag_off?` method to `control_tag?`. The name of this method was really confusing--does it indicate that the entity does _not_ have the given tag? The new method checks instead for the _presence_ of the given tag, and is named appropriately.
* Simplifies the logic of the former `control_tag_off?` method using the `Array#any?` method.
If you'd like me to roll back the other two more aggressive changes and just …
> Fixing calls to Account#control_tag_off? exceptions

- lib/killbill_client/models/helpers/tag_helper.rb
This PR simplifies the logic in `TagHelper#set_tags` by using the `Array#-` method in the ruby stdlib. The change is mostly a stylistic one (it preserves the same behavior, and isn't a performance improvement or anything), but I think it makes the logic a bit clearer and more concise. Feel free to close, though, if you don't agree or feel the change is unnecessary.
Thanks!
> Simplify logic in TagHelper#set_tags

- lib/killbill_client/utils.rb
Certain attributes that contained acronyms were not being serialized correctly (`accountCBA` for example), leading to errors like the following when updating an account:
```
KillBillClient::API::BadRequest: {"className":"com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException","code":null,"message":"Unrecognized field \"accountCba\" (class org.killbill.billing.jaxrs.json.AccountJson), not marked as ignorable (23 known properties: \"paymentMethodId\", \"name\", \"isNotifiedForInvoices\", \"currency\", \"state\", \"externalKey\", \"country\", \"postalCode\", \"timeZone\", \"locale\", \"email\", \"firstNameLength\", \"isMigrated\", \"accountId\" [truncated]])\n at [Source: org.apache.catalina.connector.CoyoteInputStream@596e8b96; line: 1, column: 525] (through reference chain: …
```
> Adding support for acronyms when camelizing attribute names

- lib/killbill_client/api/net_http_adapter.rb
Instead of `X-Killbill-Request-Id-Req`, to transmit the `request_id` option.
> Uses the standard X-Request-Id header

- lib/killbill_client/models/payment.rb
Extends Payment's find_* methods, adding the with_plugin_info argument
> Find payments with plugin info

- lib/killbill_client/models/combo_transaction.rb
- lib/killbill_client/models/transaction.rb
The `from_response` can't be used here since it doesn't check the location header if the response contains a body (even if it's an exception), so the uri attribute of the transaction was never set.
https://github.com/killbill/killbill-client-ruby/blob/master/lib/killbill_client/models/resource.rb#L84-L88
https://github.com/killbill/killbill-client-ruby/blob/master/lib/killbill_client/models/resource.rb#L114
> Fixes Location following for error responses

- lib/killbill_client/models/transaction.rb
Since the `options` object was not available in the `with_payment_failure_handling` method, the following error would occur:
```
NameError: undefined local variable or method `options' for #<KillBillClient::Model::Transaction:0x007fa11d95f950>
killbill-client-0.33.0/lib/killbill_client/models/transaction.rb:169:in `with_payment_failure_handling'
```
https://github.com/killbill/killbill-client-ruby/compare/master...andrenpaes:fix-follow-up-transaction-location-following?expand=1#diff-39d866002d606812a80fc305966ce21fL169
This change removes the refresh call from the error handling method and make sure each transaction create method explicitly calls `refresh`.
> Fixes bug when creating a transaction.

- killbill_client.gemspec
- lib/killbill_client/api/net_http_adapter.rb
- lib/killbill_client/models/invoice.rb
- lib/killbill_client/models/resource.rb
- lib/killbill_client/models/resources.rb
- lib/killbill_client/models/tenant.rb
- lib/killbill_client/models/transaction.rb
This is a list of changes to the client code to eliminate warnings and obsolescence notices emitted by 'ruby -w'. 
All specs pass.
> Remove Ruby warnings

- lib/killbill_client/models/combo_transaction.rb
- lib/killbill_client/models/transaction.rb
1. Allows the passing of the `follow_location` flag, to control if a payment should be refreshed using the `Location` header returned by a create transaction call (auth, capture, void, refund, etc)
2. Optional parameter for providing a `refresh_options` hash
> Follow location flag + refresh options

- lib/killbill_client/models/account.rb
Fix return values to methods: 'email_notifications', 'set_blocking_state', and 'invoice_payments'
> Fix methods: 'email_notifications', 'set_blocking_state', and 'invoice_payments'

- README.md
- lib/killbill_client/api/net_http_adapter.rb
Required to support JWT tokens in Kaui (Auth0 integration).
> client: add support for Bearer Token

- lib/killbill_client/models/catalog.rb
There was a recent change done as part of https://github.com/killbill/killbill-client-ruby/pull/86 that introduced a regression causing Kill Bill integration tests to [fail](https://github.com/killbill/killbill/actions/runs/5327485947/jobs/9650937682). This PR attempts to fix this.
> Fix integration test failure

- lib/killbill_client/models/account.rb
The issue is here: https://github.com/killbill/killbill-admin-ui/blob/3cc81f7239f4223f120f380a891ef1c69f17ac1b/app/controllers/kaui/invoices_controller.rb#L27
When we pass the params inside the options, it will override the default params from killbill-ruby-clients.
https://github.com/killbill/killbill-client-ruby/blob/0c897c2006f5a8e22bbc98176e91200ff02253cd/lib/killbill_client/api/api.rb#L43C17-L43C17
In this case, the params will be **includeVoidedInvoices: true** instead of **includeInvoiceComponents: true**
> Issue 120 Fix bug Invoices tab show Amount and Balance as 0

- lib/killbill_client/models/account.rb
Fix for [integration test failure](https://github.com/killbill/killbill/actions/runs/7188808294/job/19584161060#step:18:34). 
More details about this fix: 
The integration tests fail [here](https://github.com/killbill/killbill-integration-tests/blob/51968e42011ffb574b9046fe7b2a228deb803253/killbill-integration-tests/test_base.rb#L63) due to the following error:
```
TypeError: no implicit conversion of nil into Hash
```
On debugging this further, I found that [this change](https://github.com/killbill/killbill-client-ruby/pull/91) was made recently which causes this error. This PR attempts to fix this error.
> Fix for integration test failure

- lib/killbill_client/models/payment_method.rb
- lib/killbill_client/models/transaction.rb
Related ticket: https://github.com/killbill/killbill-client-ruby/issues/89
Fixed in this pull request:  
- Payment methods custom fields section - None of the code snippets in this section work. They cause a  undefined method error. I think this is because payment_method.rb does not include CustomFieldHelper as done in subscription.rb.
- Add Payment Method Custom Field and Delete Payment Method Custom Field - These endpoints need to be updated to allow creating/deleting multiple custom fields
- Payment transaction custom fields section - None of the code snippets in this section work. They cause a  undefined method error. I think this is because transaction.rb does not include CustomFieldHelper as done in subscription.rb.
> Add CustomFields to PaymentMethod and Transactions

- lib/killbill_client/models/transaction.rb
Here is the ticket: https://github.com/killbill/killbill-client-ruby/issues/89
Update:
- Add TagHelper to Transaction
> Issue 89 Add TagsHelper to Transaction

- lib/killbill_client/models/admin.rb
Related ticket: https://github.com/killbill/killbill-client-ruby/issues/89
Updates:
- Trigger an invoice generation for all parked accounts - The Ruby code for this endpoint does not accept the reason, comment parameters. I think this is required.
- Update the state of a paymentTransaction and associated payment - The endpoint requires a JSON request body corresponding to the AdminPayment resource object. See shell code for this endpoint. However, the Ruby code does not accept a JSON body. This needs to be fixed.
- Get Queue Entries endpoint accepts multiple parameters corresponding to queueName, serviceName, withHistory, etc. However, the Ruby method does not accept the corresponding parameters and thus needs to be updated.
> Sync Admin APIs with Killbill

- lib/killbill_client/models/transaction.rb
Related issue: https://github.com/orgs/killbill/projects/22/views/1?pane=issue&itemId=53996249
Update:
[Complete existing transaction using payment external key](https://killbill.github.io/slate/payment.html#complete-an-existing-transaction-using-paymentexternalkey) - This API endpoint allows completing an existing transaction using the payment external key ( without payment ID ). However, the Ruby code errors out, though the transaction gets updated correctly.
[Void existing transaction using payment external key](https://killbill.github.io/slate/payment.html#void-an-existing-payment-using-paymentexternalkey) - This API endpoint allows to void an existing transaction using the payment external key ( without payment ID ). However, the Ruby code errors out, though the transaction gets …
> Issue 89 Support external key

- lib/killbill_client/models/invoice.rb
Updates:
Trigger Invoice Group Run
Retrieve Invoice Group
Retrieve Invoice Payments
> Issue 88 Sync with Killbill Invoices APIs

- lib/killbill_client/models/role_definition.rb
- Update an existing role permissions
- Retrieve Role definition
> Issue 88 Add new Role Apis

- lib/killbill_client/models/transaction.rb
Updates: 
Mark a pending payment transaction as succeeded or failed
> Issue 88 Mark a pending payment transaction as succeeded or failed

- lib/killbill_client/api/net_http_adapter.rb
Handle the issue when the URI has already been encoded.
> Avoid double encode for encoded string
