README.md

adds syntax highlighting to the readme file code examples

add syntax highlighting to README

---

killbill_client.gemspec
spec/killbill_client/base_uri_spec.rb
spec/killbill_client/model_relation_spec.rb
spec/killbill_client/remote/api_spec.rb
spec/killbill_client/remote/model_spec.rb
spec/killbill_client/resource_spec.rb
spec/killbill_client/resources_spec.rb
spec/spec_helper.rb

I upgraded RSpec to latest stable version. Hope it will be useful

Migrate to RSpec 3.4

---

lib/killbill_client/api/net_http_adapter.rb
spec/killbill_client/encoding_spec.rb

@pierre @daliwei Please review

Fix escaping of plugin properties keys

---

lib/killbill_client/api/net_http_adapter.rb
spec/killbill_client/http_adapter_spec.rb

Add parameters for http client timeouts

---

lib/killbill_client/models/subscription.rb

https://github.com/killbill/killbill-admin-ui/pull/135

Ref killbill-admin-ui:Issue#133 - Added tag helper

---

lib/killbill_client/models/invoice.rb

Add API call to void invoces. Ref killbill/killbill#833

Add support for new voidInvoice endpoint

---

lib/killbill_client/models/credit.rb

Implement missing calls for credit resource

---

lib/killbill_client/models/account.rb
lib/killbill_client/models/invoice.rb

Add new method on 'migration_invoices' account resource.

Implement invoice missing calls.

---

lib/killbill_client/models/invoice_payment.rb

Implement missing calls for invoice payment resource

---

lib/killbill_client/models/payment.rb
lib/killbill_client/models/transaction.rb

Implement missing calls for payment resource.

---

lib/killbill_client/models/subscription.rb

Subscriptions Resource Missing Calls

---

lib/killbill_client/api/errors.rb

Ref killbill/killbill-admin-ui#130 Tenants not syncing

 To discriminate when a resource already exists

---

lib/killbill_client/models/account.rb
lib/killbill_client/models/gen/audit_log_attributes.rb
lib/killbill_client/models/helpers/audit_log_with_history_helper.rb
lib/killbill_client/models/models.rb

Ref Expose history changes in AUDIT screen killbill/killbill-admin-ui#172

 Add API call for get audit logs with history 

---

lib/killbill_client/models/account.rb
lib/killbill_client/models/custom_field.rb
lib/killbill_client/models/helpers/audit_log_with_history_helper.rb
lib/killbill_client/models/payment.rb
lib/killbill_client/models/payment_method.rb
lib/killbill_client/models/tag.rb
lib/killbill_client/models/tag_definition.rb
lib/killbill_client/models/transaction.rb

ref. killbill/killbill-admin-ui#172

 Add API call for get audit logs with history

---

lib/killbill_client/models/invoice_payment.rb

[Reff](https://github.com/killbill/killbill/issues/980)

Update 'bulk_create' method.

---

lib/killbill_client/models/invoice_item.rb

[Reff](https://github.com/killbill/slate/issues/50)

Add support for invoice tax api.

---

.github/CONTRIBUTING.md
.github/FUNDING.yml
.github/workflows/ci.yml
.github/workflows/release.yml
bin/retry
docker/docker-compose.ci.mysql.yml
docker/docker-compose.ci.postgresql.yml
killbill_client.gemspec
lib/killbill_client.rb
lib/killbill_client/api/net_http_adapter.rb
spec/killbill_client/http_adapter_spec.rb

This is required for https://github.com/killbill/killbill-admin-ui-standalone/issues/39.

Configurable timeouts

---

lib/killbill_client/models/catalog.rb
lib/killbill_client/version.rb

Here is the following ticket: https://github.com/killbill/killbill-admin-ui/issues/309
Add a new parameter to the function to support return catalog by account.

309 Per account catalog support

---

lib/killbill_client/models/transaction.rb

Include TagHelper to Transaction

Include TagHelper

---

lib/killbill_client/models/invoice.rb
lib/killbill_client/models/payment.rb
lib/killbill_client/models/payment_method.rb
lib/killbill_client/models/subscription.rb

Sync with Killibill API. Related ticket is here: https://github.com/killbill/killbill-client-ruby/issues/89

Issue 89 Sync Killbill API for Invoices, Payments, PaymentMethods,Subscriptions

---

lib/killbill_client/models/subscription.rb

Related issue: https://github.com/killbill/killbill/actions/runs/8289680271/job/22694076149

Add missing audit parameter

---

lib/killbill_client/models/invoice.rb

.blank? will not work with non-Rails projects.

Change .blank? to .empty?

---

lib/killbill_client/models/custom_field.rb

Related issue: https://github.com/orgs/killbill/projects/22/views/1?pane=issue&itemId=53996249
Update:
- [List all custom fields](https://killbill.github.io/slate/custom-field.html#list-all-custom-fields) - This api endpoint is missing the Audit parameter that is present in other clients.

Issue 89 Add audit to batch API

---

lib/killbill_client/models/tenant.rb

Updates:
- Tenant push notifications
- Tenant System properties configuration
- Tenant Payment States Machine configuration

Issue 88 Add new Tenants APIs

---

lib/killbill_client/models/account.rb

Updates:
Retrieve Paginated Invoices
Retrieve Paginated Bundles

Issue 88 Sync with Killbill Accounts APIs

---

lib/killbill_client/models/catalog.rb

Update:
- Validate a catalog XML

Issue 88 Add Validate catalog API
